In [1]:
n=4
ans=[]
x=1
for i in range(n,0,-1):
    g=x
    x=i+x
    for j in range(g,x):
        a=a+str(j)+'*'

        b=b+"*"+str(j+(i*i))

   
    if n-i!=0:
        ans.append('-'*(2*(n-i))+a[:-1]+b)
        
    if n-i==0:
        ans.append(a[:-1]+b)
        
    a,b='',''
for i in ans:
    print(i)

NameError: name 'a' is not defined

In [ ]:
a=[4,2,2,2,4]
n=len(a)
p=False
temp=0
ans=[]
j=0
#for i in range(n):
while j<n-1:
        if a[j]>a[temp] :
            if a[j+1]<a[temp] :
                ans.append([temp,j])
                p=True
            if j==n-2:
                ans.append([temp,j+1])
                p=True
                
                
            
        if a[temp]>a[j]:
            temp=j

        print(temp)
        j+=1
            
if p :print(ans)
else:print(0)

In [ ]:
s='aaabbaa'
n=len(s)
ans=[]
h=[]
for i in range(n):
    for j in range(i+1,n+1):
        if s[i:j]==s[i:j][::-1]:
            ans.append(s[i:j])
for i in ans:
    h.append(len(i))
    
print(ans[h.index(max(h))])

In [ ]:
arr=[1,2,3,4,5]
l=len(arr)-1
arr = arr[l:]+arr[:l]
print(arr)

In [ ]:
def rotate(a, n):
    f=a[n-1]
    for i in range(n-1,0,-1):
        a[i]=a[i-1]
    a[0]=f
a=[1,2,3,4,5]    
rotate(a,5)
print(*a)

In [ ]:
s='ecfbefdcfca'
t='badfcbebbf'
ctr=0
print(len(s),len(t))
if len(s)==len(t):
    for i in range(len(s)):
        if s[i]!=t[i]:
            ctr+1
            
if len(s)<len(t):
    for i in range(len(t)):
                if s[i]==t[i]:
                    continue
                else:
                    temp=s[i:]
                    s=s[:i]+t[i]+s[i:]
                    ctr+=1
                    
if len(s)>len(t):
    ctr1,ctr2=0,0
    x=len(s)-len(t)
    s1=s[x:]
    s2=s[0:len(s)-x]
    print(s1,s2)
    for i in range(len(s1)):
        if s1[i]!=t[i]:
            ctr1+=1
            
    for i in range(len(s2)):
        if s2[i]!=t[i]:
            ctr2+=1
            
    print(ctr1,ctr2)       
    ctr=min(ctr1,ctr2)
            
            
    
    
    
                    
print(ctr)

In [ ]:
import collections
s='gandmarao'
p='ndr'
li=list(p)
dict1=collections.Counter(s)
for i in p:
    if dict1[i]>=1:
        continue
    else:
        print(-1)
                
if len(p)>len(s):
        print(-1)
            
if p==s:
        print(p)
u=False
ans=[]
for j in range(len(s)-1,len(p)-1,-1):
        for i in k:
            if i in s[0:j+1]:
                u=True
                continue
                
            if i not in s[:j+1]:
                u=False
                break
                
        if u:
            ans.append(s[:j+1])
                            

print(ans)
            

In [ ]:
s='gandmarao'
p='ndr'
k=list(p)
u=False
ans=[]
for j in range(len(s)-1,0,-1):
        for i in k:
            if i in s[0:j+1]:
                u=True
                continue
                
            if i not in s[:j+1]:
                u=False
                break
                
        if u:
            ans.append(s[:j+1])

r=ans[len(ans)-1]                   
d=False
ans2=[]
for j in range(0,len(r)):
    for i in k :
        if i in r[j:]:
            d=True
            continue
            
        if i not in r[j:]:
            d=False
            break
            
    if d:
        ans2.append(r[j:])
      
final=ans2[len(ans2)-1]
print(final)

In [ ]:
import numpy as np
n=5
prod=1
if n == 0 :
    prod=1
        
else:
    for i in range(1,n+1):
        prod=prod*i
                
l=[]
while prod>0:
    l.append(prod%10)
    prod=prod//10
    
print(np.reverse(l))

In [ ]:
n=20

temp,r=0,0
s=10**n
sumx=0
if n >0 and n<10:
    print(n*s)
    
else:
    h=n//9
    for i in range(h):
        r=(r*10)+9
        sumx=sumx+9
    temp=((n-sumx)*(10**h))+r
    print(temp*s)


In [ ]:
import collections
arr=[[0 ,0, 0 ,1,0 ,0],[0 ,0 ,0 ,1, 0, 1]]
ans=[]
for i in arr:
    dict=collections.Counter(i)
    ans.append(dict[1])
    
x=ans.index(max(ans))
    
if ans.count(max(ans))>1:print(-1)
else:print(x)

In [ ]:
a=[34, 8, 10, 3, 2, 80, 30, 33, 1]
x=[]
ans=[]
for i in a:
    x.append(i)
    
x.sort()
m=max(a)
n=a.index(m)
for i in range(len(a)):
    if i is not n and n>i :
        ans.append(n-i)
print(max(ans))

In [ ]:
def merge(a,l,m,r):
    
    n1= m - l + 1
    n2=h-m
    tl=[0]*n1
    tr=[0]*n2
    for i in range(n1):
        tl[i]=a[i]
        
    for j in range(n2):
        tr[j]=a[j]
        
    i,j,k=0,0,1
    while i<n1 and j<n1:
        if tl[i]<tr[j]:
            a[k]=tl[i]
            k+=1
            i+=1
            
            
        if tl[i]>tr[j]:
            a[k]=tr[j]
            k+=1
            j+=1
            
            
    if i<n1:
        a[k]=tl[i]
        i+=1
        k+=1
        
    if j <n2:
        a[k]=lr[j]
        j+=1
        k==1
        
        
def mergesort(a,l,h):
    if l<h:
        m=(l+h)//2
        mergesort(a,l,m)
        mergesort(a,m+1,h)
        merge(a,l,m,h)
        
        
a=[4,2,65,12,11,13,1,0,9]
print(a)
mergesort(a,0,len(a))
print(a)
        

In [ ]:
import math
from itertools import product

x=[1,5,5,5,2]
ctr=0
n=len(x)
temp,l=[],[]
for i in range(0,n):
    temp.append(i)
    
d=list(product(temp,temp))
for i in d:
    if [i[1],i[0]] not in d:
        if i!=[i[0],i[0]]:
            l.append(i)
        
print(l)
h=l[0][1]

for i in l:
    g=math.gcd(x[i[0]],x[i[1]])
    l=(x[i[0]]*x[i[1]])/g
    if g==l:
        ctr+=1
            
print(ctr)

In [ ]:
x=[1,5,5,5,2]
n=len(x)
temp,l=[],[]
for i in range(1,n+1):
    temp.append(i)
    
d=list(product(temp,temp))
for i in d:
    if [i[1],i[0]] not in d :
        if i!=[i[0],i[0]]:
            l.append(i)
        
print(l)

In [ ]:
import math
x=[1,5,5,5,2]
temp=[]
ctr=0
for i in range(len(x)):
    for j in range(i+1,len(x)):
        temp.append([x[i],x[j]])    
print(temp)

for i in temp:
    g=math.gcd(i[0],i[1])
    l=(i[0]*i[1])/g
    if l==g:
        ctr+=1
        
print(ctr)


In [7]:
x=[[2 ,3, 5, 4, 1],[4, 2 ,1 ,5 ,6]]
#x=[[1,2,3],[1,4,2]]
#x=[[1,2],[2,1]]
#x=[[1,2],[3,4]]
mp=0
ans=[]
gp=x[0].copy()
wp=x[1].copy()    
gp.sort()
wp.sort()
print(x)
print(gp,wp)
for i in range(0,len(x[0])):
    print(i)
    print(x[0][i],x[1][i])
    print(gp.index(x[0][i]),wp.index(x[1][i]))
    print(gp.index(x[0][i])+wp.index(x[1][i]))
    print('------------------')
    ans.append(gp.index(x[0][i])+wp.index(x[1][i]))


print(ans)

[[2, 3, 5, 4, 1], [4, 2, 1, 5, 6]]
[1, 2, 3, 4, 5] [1, 2, 4, 5, 6]
0
2 4
1 2
3
------------------
1
3 2
2 1
3
------------------
2
5 1
4 0
4
------------------
3
4 5
3 3
6
------------------
4
1 6
0 4
4
------------------
[3, 3, 4, 6, 4]


In [21]:
def fuck(a,n,i,cur,h):
    global ans
    if cur>h:return
    if i==n:
        ans=min(ans,h-cur)
        return
    print(ans)
    fuck(a,n,i+1,cur+a[i],h)
    fuck(a,n,i+1,cur,h)

ans=8888888
a=[1,2,5,7,11]
h=10
n=len(a)
global ans
fuck(a,n,0,0,h)

print(ans)

8888888
8888888
8888888
8888888
8888888
2
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [24]:
import numpy as np
num=455
n = [int(x) for x in str(num)]
print(np.prod(n))

100


In [1]:
for i in range(1,len(gp)):
    mp=(len(gp)-1)-i + (len(wp)-wp.index(wp[gp.index(x[0][i])]))
    print(mp)
    
    ans.append(mp)
 

NameError: name 'gp' is not defined

In [34]:
import collections
import sys
x=[1,4,4,2,2,2]
freq=[]
bool=True
g=True
dict=collections.Counter(x)
key=list(dict.keys())
val=list(dict.values())
print(key[1],val[1])
for k,v in dict.items():
    freq.append(v)
for i in collections.Counter(freq).values():
    if i!=1:
        bool=False
if bool:
    for i in key:
            for j in range(x.index(i),x.index(i)+val[x.index(i)]):
                if x[j]!=i:
                    g=False
                    print('no')
                    break

    if g:
        print('yes')

else:
    print('no')


4 2


IndexError: list index out of range

In [14]:
s='banana'

l=list(s)
vo=[]
co=[]
for i in l:
    if i.lower() in 'aeiou':
        if i not in vo:vo.append(i)
    else:
        if i not in co:
            co.append(i)
tom=[]#vowel
x=[]
jerry=[]#consonetnt
y=[]
for k in vo:
    for i in range(1,len(s)-l.index(k)+1):
        tom.append(s[l.index(k):l.index(k)+i])
        x.append(s.count(s[l.index(k):l.index(k)+i]))
        
for k in co:
    for i in range(1,len(s)-l.index(k)+1):
        jerry.append(s[l.index(k):l.index(k)+i])
        y.append(s.count(s[l.index(k):l.index(k)+i]))
        
print(tom)
print(x)
print(sum(x))
print('__________________----------------------______________________')
print(jerry)
print(y)
print(sum(y))

print(vo,co)


['a', 'an', 'ana', 'anan', 'anana']
[3, 2, 1, 1, 1]
8
__________________----------------------______________________
['b', 'ba', 'ban', 'bana', 'banan', 'banana', 'n', 'na', 'nan', 'nana']
[1, 1, 1, 1, 1, 1, 2, 2, 1, 1]
12
['a'] ['b', 'n']


In [15]:
string='banana'
vowels = ('A', 'E', 'I', 'O', 'U')
n = len(string)
total = n*(n+1)/2
    
k = sum([n-i for i in range(n) if string[i] in vowels])
s = total-k
       
if k==s:
        print("Draw")
elif k>s:
        print(f"Kevin {int(k)}")
else:
        print(f"Stuart {int(s)}")

Stuart 21


In [3]:
import numpy as np
n=3
a=2
x=[[a]*n]*n
for i in range(n):
    print(x[i])

print(x[0][n-1])
temp=x[0][n-1]
x[0][2]=0
print(x)
for i in range(n):
    print(x[i])
x=np.array(x)       
x=x*temp
for i in range(n):
    print(x[i])
            
    

[2, 2, 2]
[2, 2, 2]
[2, 2, 2]
2
[[2, 2, 0], [2, 2, 0], [2, 2, 0]]
[2, 2, 0]
[2, 2, 0]
[2, 2, 0]
[4 4 0]
[4 4 0]
[4 4 0]


In [14]:
import numpy as np
x=[[2,2,2],[2,2,2],[2,2,2]]
temp=x[0][2]
x[0][2]=0
ans=[] 
ans.append(temp)
x=np.array(x)       
x=x*temp
print(x)
print(ans)
ctr=0
x=list(x)
for i in range(n):
    for j in range(n):
        if (i==0 and x[i][j+1]==0) or (i==j) or (j==n-1 and x[i-1][j]):
            temp=x[i][j]
            ctr+=1
            x[i][j]=0
    ans.append(temp**ctr)
    x=x*temp
    
            
print(x)
print(ans)        


[[4 4 0]
 [4 4 4]
 [4 4 4]]
[2]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [24]:
a=[5, 3 ,2 ,8 ,4 ,1]
ctr=[]
temp=a.copy()
temp.sort(reverse=True)
for i in range(len(a)):
    x=temp[0:i]
    if sum(x)>=sum(temp[i:]):

        ctr.append(len(x))


                
return(min(ctr))

[8, 5, 4, 3, 2, 1]
2


In [25]:
a=[5, 3 ,2 ,8 ,4 ,1]
m=sum(a)
temp=a.copy()
temp.sort(reverse=True)
for i in range(len(temp)):
    if 

23


In [26]:
0

def findSubstring(s, k):
    vowels = "aeiou"
    return_output = ["Not found!"]
    max_countt = 0
    
    # loop size such that index don't gets out of range
    length = len(s)-k+1
    for i in range(length):  

        # temporary storage of vowel count
        sum_count = 0  

        # getting string of desire size
        output = s[i:i+k]

        # count of vowels in the string
        for vowel in vowels:
            sum_count += output.count(vowel) 

        # if vowels in the string is greater than string having max vowels
        # replace the max vowel string and number of max vowel count
        if max_countt < sum_count:
            return_output = output
            max_countt = sum_count
    
    # return output
    return "".join(return_output)

print(findSubstring("azerdii", 5))

erdii


In [27]:
#fetch all substrings
string_is = 'azerdii'
sub = 5
length = len(string_is)
sub_ar = [string_is[i:j+1] for i in range(length) for j in range(i,length)]
#print(sub_ar)

#fetch substrings of a length = 5
sub_ar_is = []
for each in sub_ar:
  if len(each) == 5:
    sub_ar_is.append(each)
print(sub_ar_is)
data_dict = {}
data = ['a','e','i','o','u']
for each in sub_ar_is:
  count = 0
  for each_is in data:
    count = count + each.count(each_is)
  data_dict.update({each:count})

print(data_dict)
print("Substring is: ", max(data_dict, key=data_dict.get))

['azerd', 'zerdi', 'erdii']
{'azerd': 2, 'zerdi': 2, 'erdii': 3}
Substring is:  erdii


In [6]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[9,8,7],[6,5,4],[3,2,1]]
temp,temp2=[],[]
ans=[]
for i in range (3):
    for j in range(3):
        for k in range(3):
            temp.append(a[i][k]*b[k][j])
        #print(temp)
        temp2.append(sum(temp))
        temp=[]
    ans.append(temp2)
    temp2=[]
    
print(ans)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


In [16]:
n=4
m=3
e=[[1,2],[2,3],[2,4]]
visited=[]
p=[]
new=[]
temp=[]
for i in range(n):
    for j in range(n):
        temp.append(0)
    new.append(temp)
    temp=[]
for i in e:
    x=i[0]-1
    y=i[1]-1
    new[x][y]=1
    
print(new)        



[[0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0]]


In [17]:
!pip install gtts



[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
!pip install playsound


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
from gtts import gTTS
from playsound import playsound
audio='speech.mp3'
l='en'
sp=gTTS(text="hello world",lang=l,slow=False)
sp.save(audio)
playsound(audio)


    Error 263 for command:
        open speech.mp3
    The specified device is not open or is not recognized by MCI.

    Error 263 for command:
        close speech.mp3
    The specified device is not open or is not recognized by MCI.
Failed to close the file: speech.mp3


PlaysoundException: 
    Error 263 for command:
        open speech.mp3
    The specified device is not open or is not recognized by MCI.

In [19]:
import math
ans=[]
w=[]
wr=[]    
n=3
for i in range(1,n):
        if (n-i)%2==0:
            w.append(i)
            w.append((n-i)//2)
            wr.append((n-i)//2)
            wr.append(i)
         
        p=i+(n-i)//2
        x=math.factorial(p)-2*(math.factorial(i))
        if x!=0:
            ans.append(x)
        ans.append(w)
        ans.append(wr)
        w=[]
        wr=[]

ans.append(n)
if n%2==0:ans.append(n//2)
print(ans)
print(len(ans))

[[1, 1], [1, 1], -2, [], [], 3]
6


In [36]:
n=7
ctr=0
ans=[]

while (n!=0):
    print(n)
    if n==1:
        ans.append(0)
        break
    if n%2==0 and n!=1:
            n=n-(n//2)
            ans.append(n)
            continue
            
    if n%2!=0 or n==1:
            n=n-((n+1)//2)
            ans.append(n)
            continue
            
        
print(ans)

7
3
1
[3, 1, 0]


In [ ]:
#optimal-merge-pattern

In [1]:
l=[20,30,10,5,30]
x=[]
ans=[]
for i in range (0,len(l)):
    x.append(l[i])
   
x.sort()

while True:
    temp=x[0]+x[1]
    ans.append(temp)
    x.pop(0)
    x.pop(0)
    x.append(temp)
    x.sort()
    if len(x)==1:
        break
print(sum(ans))
print(x)

205
[95]


In [1]:
!pip install big-o-calculator


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from bigO import BigO
from bigO import algorithm
from random import randint

In [3]:
fname=input("Enter algorithm name:")

Enter algorithm name:gagu_beti


In [6]:
def fname(l):
    x=[]
    ans=[]
    for i in range (0,len(l)):
        x.append(l[i])

    x.sort()
    flag=True
    while True:
        temp=x[0]+x[1]
        ans.append(temp)
        x.pop(0)
        x.pop(0)
        x.append(temp)
        x.sort()
        if len(x)==1:
            break
    print(sum(ans))
    
def TimeComplexity(functionname):
    lib = BigO()
    cmplx = lib.test(functionname, "random")
    cmplx = lib.test(functionname, "sorted")
    cmplx = lib.test(functionname, "reversed")
    cmplx = lib.test(functionname, "partial")
    cmplx = lib.test(functionname, "Ksorted")
l=[20,30,10,5,30]
fname(l)
TimeComplexity(fname)

205
Running fname(random array)...
-328
-328
-328
-328
-328
-181098
-181098
-181098
-181098
-181098
-152990199
-152990199
-152990199
-152990199
-152990199
-166744295161
-166744295161
-166744295161
-166744295161
-166744295161


KeyboardInterrupt: 

In [ ]:
#knapsack problem==

In [36]:
p=[10,5,15,7,6,18,3]
w=[2,3,5,7,1,4,1]
x=[]
u=[]
q=15
sum=0
aux=[0]*len(p)
for i in range(len(p)):
    u.append(p[i]/w[i])   
print (u)
for i in u:x.append(i)    
x.sort(reverse=True)
print(x)
while True:
    px=x[0]
    ind=u.index(px)
    if w[ind]<q:
        aux[ind]=1
        q-=w[ind]   
        x.pop(0)
    else:
        aux[ind]=(q)/w[ind]
        q=0
        x.pop(0)  
        
    print(q,'-----------',aux[ind],'-------------',w[ind])
    if q==0:break
    
for i in range(len(p)):
    sum=sum+(aux[i]*p[i])
print(sum)    
print(aux)  

[5.0, 1.6666666666666667, 3.0, 1.0, 6.0, 4.5, 3.0]
[6.0, 5.0, 4.5, 3.0, 3.0, 1.6666666666666667, 1.0]
14 ----------- 1 ------------- 1
12 ----------- 1 ------------- 2
8 ----------- 1 ------------- 4
3 ----------- 1 ------------- 5
0 ----------- 0.6 ------------- 5
43.0
[1, 0, 0.6, 0, 1, 1, 0]


In [ ]:
#longest common subsequence(dynamic programming approach)

In [2]:
x=['a','b','c','d']
y=['b','d']
t = [ [None]*(len(x)+1) for i in range(len(y)+1)]
for i in range(len(y)+1):
    for j in range(len(x)+1):
        t[i][0]=0
        if i==0:
            t[i][j]=0
 
for i in range(1,len(y)+1):
    for j in range(1,len(x)+1):
        if y[i-1]==x[j-1]:
            t[i][j]=(1+t[i-1][j-1])
            
        else:
            t[i][j]=max(t[i][j-1],t[i-1][j])
print(t)
print(max(max(t)))

[[0, 0, 0, 0, 0], [0, 0, 1, 1, 1], [0, 0, 1, 1, 2]]
2


In [30]:
x=[[6,2,2,2],[5,10,10,0]]
print(max(x))

[6, 2, 2, 2]


In [41]:

r=3
c=3
m = [[1, 3, 5], 
     [2, 6, 9], 
     [3, 6, 9]]
t=[]
for i in range(r):
    for j in range (c):
        t.append(m[i][j])
t.sort()        
print(t)
if len(t)%2==0:
    print((t[len(t)//2]+t[(len(t)-1)//2])//2)
else:
    print(t[(len(t))//2])

[1, 2, 3, 3, 5, 6, 6, 9, 9]
5


In [49]:
#zero-one knapsack problem

In [50]:

v = [1,2,3]
w= [4,5,1]
W = 4
pw=[]
ans=[]
x=[]
for i in range(len(v)):
    pw.append(v[i]/w[i])
    x.append(v[i]/w[i])
 
x.sort(reverse=True)
for i in range(len(v)):
    temp=x[0]
    if w[pw.index(temp)]<=W:
        ans.append(v[pw.index(temp)])
        W-=w[pw.index(temp)]
        x.pop(0)
print(pw)
print(x)
print(ans)
print(sum(ans))

[0.25, 0.4, 3.0]
[0.4, 0.25]
[3]
3


In [17]:
a= [76, 91, 3, 22, 79, 57, 83 ,41, 9, 76, 47, 14]
n=len(a)
k=6
leng=0
n=len(a)
ans=[]
a.sort()
while (max(a)- min(a))>k:
    if max(a[1:])-min(a[1:])<=k:
        a.pop(0)

        break
        
    if max(a[:len(a)])-min(a[:len(a)])<=k:
        a.pop(len(a)-1)
        
        break
        
    a.pop(0)
    a.pop(len(a)-1)
    
print(n-len(a))

11


In [8]:
a = [900, 1100, 1235]
d = [1000, 1200, 1240]
ctr=0
plat=[]
for i in range(1,len(a)):
    if a[i]>=d[i-1]:
            continue
    else:
        ctr+=1
        
if ctr not 0:print(ctr)
else:print(1)

0


In [11]:
a=[900, 940, 950, 1100, 1500, 1800]
b=[910, 1200, 1120, 1130, 1900, 2000]
ctr=1
st=[b[0]]
for i in range(1,len(a)):
    if a[i]<st[0]:
        st.append(b[i])
        st.sort()
        
    else:
        st.pop(0)
        st.append(b[i])
        st.sort()
        
print(st)

[1200, 1900, 2000]


In [6]:
ctr=0
pos=0
a = [2, 3, 1, 1, 2, 4, 2, 0, 1, 1]

while True:
    x=a[pos]
    #print(x,'--')
    #print(a[pos+1:a[pos]+pos+1])
    a[:pos]=[0]*pos
    if pos+a[pos]>=len(a)-1:
        ctr+=1
        break
    pos=a.index(max(a[pos+1:a[pos]+pos+1]))
    ctr+=1
    #print(pos)
    #print(a)
   
print(ctr)

4


In [48]:
a=[0,1,2,3,4,5,6,7]

print(a[:4])
a[:4]=[0]*4
print(a)

[0, 1, 2, 3]
[0, 0, 0, 0, 4, 5, 6, 7]


In [11]:
a=[2,1,4,2,5]
n=len(a)
ans=[]
temp=[0]*n

for i in range(n):
    temp[a[i]-1]+=1  
print(temp)
            


[1, 2, 0, 1, 1]


In [8]:
import numpy as np
p = [100, 80, 60, 70, 60, 75, 85]
ans=[]
ans.append(1)
for i in range(1,len(p)):
    if p[i-1]>p[i]:ans.append(1)
        
    else:
        x=np.array(p[:i+1])
        ans.append(np.count_nonzero((x>p[i]) == False))
        
print(ans)
        

[1, 1, 1, 2, 1, 4, 6]


In [7]:
s='aaaa'
n=len(s)
ans=[]
for i in range(n-1):
    print(s[:i+1],s[n-i-1:])
    if s[:i+1]==s[n-i-1:]:
        ans.append(len(s[:i+1]))

print(ans)        
print(max(ans))    

a a
aa aa
aaa aaa
[1, 2, 3]
3


In [20]:
#mango tree problem----

In [23]:
a=[[0,1,1,0,0,0],
   [1,0,0,1,1,0],
   [0,1,0,0,0,0],
   [0,1,1,0,0,1],
   [1,0,0,1,1,0],
   [0,1,0,0,0,0]]
r=len(a)
c=len(a[0])
temp=[]
x=[]
for i in range(r):
    for j in range(c):
        x.append(0)     
    temp.append(x)
    x=[]
    
for i in range(r):
    for j in range(c):
        if i==0 and j==0:temp[i][j]=a[i][j]
            
        if i==0 and j>0:temp[i][j]=a[i][j]+temp[i][j-1]
            
        if j==0 and i>0:temp[i][j]=a[i][j]+temp[i-1][j]
            
        if i>0 and j>0:
            temp[i][j]=temp[i][j-1]+temp[i-1][j]-temp[i-1][j-1]+a[i][j]
            
#print(temp)
ans=0
for i in range(r):
    for j in range(c):
        p1=temp[i][j]
        p2=temp[i][c-1]-p1
        p3=temp[r-1][j]-p1
        p4=temp[r-1][c-1]-(p1+p2+p3)
        #print(p1,p2,p3,p4)
        #print()
        z=min(p1,p2,p3,p4)
        if z>ans:ans=z
            
print ("minimum number of trees ramu atleast has--",ans)

minimum number of trees ramu atleast has-- 3


In [ ]:
#stock spanning problem

In [13]:
a=[100,80,60,70,60,75,85]
ans=[]
s=[]
s.append(0)
ans.append(1)
for i in range(1,len(a)):
        if a[i]<a[i-1]:
            s.append(i)
            ans.append(1)
        else:
            while(a[i]>a[s[len(s)-1]]):
                s.pop()
            ans.append(i-s[len(s)-1])
        
                
 
print('stock spanning array---',ans)

stock spanning array--- [1, 1, 1, 2, 1, 4, 6]
